[versions]
# Project versions
projectMinSdkVersion = "24"
projectTargetSdkVersion = "35"
projectCompileSdkVersion = "35"
projectVersionName = "1.0"
projectVersionCode = "1"
projectApplicationId = "com.multi.module.template"

coroutines = "1.10.2"

agp = "8.13.1"
androidTools = "31.13.1"
kotlin = "2.0.21"

room = "2.7.2"
ksp = "2.0.21-1.0.25"

hilt = "2.51.1"
hiltCompiler = "1.2.0"
hiltNavigationCompose = "1.2.0"
hiltExt = "1.1.0"

coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
jetbrainsKotlinJvm = "2.0.21"
appcompat = "1.6.1"
material = "1.10.0"

desugar_jdk_libs = "2.0.4"

timber = "5.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }


desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

# room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }

#dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
#hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
#androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltCompiler" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Gradle
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }
room = { id = "androidx.room", version.ref = "room" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# Custom Convention Plugin
multi-module-android-application = { id = "multi.module.android.application", version = "unspecified"}
multi-module-android-application-compose = { id = "multi.module.android.application.compose", version = "unspecified"}
multi-module-android-library = { id = "multi.module.android.library", version = "unspecified" }
multi-module-android-library-compose = { id = "multi.module.android.library.compose", version = "unspecified" }
multi-module-android-presentation-ui = { id = "multi.module.android.presentation.ui", version = "unspecified" }
multi-module-jvm-library = { id = "multi.module.jvm.library", version = "unspecified" }
multi-module-android-room = { id = "multi.module.android.room", version = "unspecified" }
multi-module-android-hilt = { id = "multi.module.android.hilt", version = "unspecified" }


[bundles]
application = [
    "androidx-core-ktx",
    "junit",
    "androidx-junit",
    "androidx-espresso-core",
    "androidx-lifecycle-runtime-ktx",
    "androidx-appcompat"
]

compose = [
    "androidx-activity-compose",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-compose-material3",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-hilt-navigation-compose"
]

compose-debug = [
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-test-manifest",
    "androidx-compose-ui-test-junit4"
]